//list of insults ripped from another bot  
module.exports = [
  ' Shut your fucking mouth you\'re just really fucking dense.',
  ' Grab a dick and eat it whole, ninny.',
  ' You\'re a stupid cunt suck my dick.',
  ' Go ahead and run your mouth, pussy I don\'t give a fuck.',
  ' Motherfucking tryina be a man when ya nose all runny.',
  ' Go back to pre-k put your bag in your cubby.',
  ' You got a sad life, go to fucking hell.',
  ' Are you stupid or disabled, I can\'t fucking tell.',
  ' Stop bouncing on my dick, cunt.',
  ' You pathetic fucking pussy.',
  ' Man up, bitch.',
  ' Can\'t you take a fucking insult like a man?',
  ' You ain\'t shit.',
  ' You ain\'t shit, nonce.',
  ' Suck my dick, you a bitch.',
  ' Don\'t fuck around with me.',
  ' You\'re fucking pathetic.',
  ' Get the fuck off of my dick.',
  ' Stop bobbing on my dick.',
  ' I don\'t got time for another little bitch',
  ' Y\'all are fucking trash.',
  ' Stay the fuck out of my business.',
  ' I don\'t fuck with pussies, call me gay.',
  ' Run down the gutter like subway surfers, bitch.',
  ' Crawl down the sewers back to where you belong, trash.',
  ' I\'ll help you tie your nooses if you don\'t know how.',
  ' Fucking dog, I\'ll smack at your teeth.',
  ' I\'ll fuck you with a radiator pipe.',
  ' Stop fucking around like a cam whore.',
  ' Yeah go pop it off to some gay shit.',
  ' You\'re a fucking load of shit.',
  ' Don\'t be fucking crying when I\'m smashing your face in with a bottle.',
  ' Keep laughing, little cunt.',
  ' Nice hunch, cunt.',
  ' I can\'t answer at the moment I got pussy in my mouth, my face, depending on the nationality I get a different taste.',
  ' Suck a dick and a ball sack.',
  ' Y\'all are just fucking whack.',
  ' Take me out to the back of the shed, and shoot me in the back of the head.',
  ' When you read my lips I know you feel all cold, but I promise you my heart is made of gold.',
  ' Not all men are created equal, those like you are meant to be looked down on.',
  ' Come back when you\'re in the state that I\'m in, yeah constant fear and misery',
  ' I hope you cherry pick your way to hell.',
  ' What kind of shit are you trying to sell?',
  ' Idiocracy you breathe.',
  ' You\'re fucking illiterate.',
  ' Check your fucking self before you pick these damn fights that you can\'t own.',
  ' Own your shit, pussy.',
  ' I hate fucktards like you.',
  ' Ya fucking fetus, crawl back into mum\'s womb for me.',
  ' Inbred fucking degenerates always shitting on everything.',
  ' Don\'t be fucking me, cause bet your ass you\'re hearing it.',
  ' I hate it when inbreds think they\'re the shit.',
  ' Closed fists, fucking mad ninny throwing fits with your fat old tits.',
  ' I\'m motherfucking pink on the top of my dick but when I smack it on ya girl\'s lips she gon\' be sick.',
  ' Suck my dick, shitlips, you don\'t know me.',
  ' You ain\'t shit, you fucking bigot.',
  ' Take the fucking bull by its horns you fucking pussy.',
  ' Jerk it off to some gay shit.',
  ' I\'ll fuck you in the mouth again.',
  ' Fucking kid I\'ll smack out your teeth.',
  ' Low on self esteem so you run on memes.',
  ' Go suck yourself a fat one.',
  ' Shut your fucking mouth, cunt, don\'t go around running your fucking mouth like that.',
  ' Go away and stay away you worthless piece of garbage.',
  ' Bruh you crossed the fucking line there.',
  ' The fuck are you rambling on about??',
  ' So fucking delicate like mommy\'s fine china.',
  ' Shut your fucking mouth you dense motherfucker.',
  ' Man up bitch, come at me you fucking pussy.',
  ' This server\'s full of degenerates.',
  ' Get the fuck out, I don\'t allow inbreds running around in my fucking house..',
  ' What a load of shit.',
  ' Get the fuck out, this server\'s not a litterbox for you to shit all over in. You primitive fucking ape.',
  ' Fucking abort, do not engage.',
  ' Don\'t fucking tell people what to do you entitled prick.',
  ' Fucking pretencious ass ninny.',
  ' Perhaps try to be less of a twat.',
  ' End of the line for you, boy.',
  ' I don\'t have time to fuck around with inbred fucking autists.',
  ' I\'ll fucking wreck you, cunt.',
  ' I will fucking explode.',
  ' You want to fucking try me?',
  ' White is right, and white is good, keep those ninnies, back in the hood.',
  ' God fucking damn it I love attacking retards.',
  ' Robots are very capable, unlike your disabled ass.',
  ' You\'re gonna be fucking dead, kiddo.',
  ' I\'ll blow a cap in your head if you sprout that shit again.',
  ' Miss me with that bullshit.',
  ' Stop acting like you\'re some real shit, aight, you\'re just a fucking load of crap.',
  ' I need my daily dose of dad please.',
  ' Shut the fuck up, cunt.',
  ' If you have complaints please wait your turn and line up.',
  ' What momma’s boy and a teacher\'s pet, pimple face, asswipe, looking like they just had a gyne-cologist stick five fingers in your ass, no lube.',
  ' So whatcha gonna do, cunt?',
  ' I only joke about diseases and reference that only you can catch.',
  ' I\'m sicker than the AIDS, flus, hepatitis, and SARS.',
  ' A six gauge ring couldn\'t wrap around my dick.',
  ' If you think you’re fucking grown up, keep breathing heavy with your keyboard and fedora.',
  ' Go outside and ride a bike or something, and get laughed at by kids to remind you that you are nothing.',
  ' Go sit at your computer and open up Google Chrome, look up tutorials on how to hang yourself at home.',
  ' I go twelve inch deep in the pussy, after twenty minutes you can drive a fucking Jeep in the pussy.',
  ' Your girlfriend\'s always sucking on my dick like a Slim Jim stick, so next time you go down on her clit, tell me how my dick tastes, tell me how my motherfucking dick tastes.',
  ' Please check yourself before you go around sprouting bullshit like that.',
  ' You aren\'t worth a dime, bitch.',
  ' I\'ll fucking wreck you, cunt.',
  ' You\'re fucking dead, kiddo',
  ' You must feel like shit \'cause you are.',
  ' You\'re a fucking waste of my time and energy, cunt.',
  ' You look like you came straight out of the African wild.',
  ' You\'re disposable like the paper plates you eat off cause you can\'t afford anything else.',
  ' Your relationship status is as dry as your sense of morality.'
]